### ISSUE TITLE
Tooltips display too many digits when the number is a circulating decimal

### ISSUE THREAD

**Issue by Szong06** [computationalmystic/augur-group10#6]
**Describe the bug:**
Tooltips display too many digits when the number is a circulating decimal in chart.

**To Reproduce:**
1. Go to page for any project.
2. Scroll down to any graph.
3. Hover over a data point which has a circulating decimal value.
4. See the number.

**Expected behavior:**
The tooltips should show 2 digits after the point for each decimal.

**Screenshots**
![Screen Shot 2019-05-05 at 10 07 54 PM](https://user-images.githubusercontent.com/46948288/57205245-d74ba000-6f82-11e9-85d7-f47e9eaf5803.png)

**Desktop:**
 - OS: macOS V10.14.4
 - Browser: Chrome v 74.0.3729.108
 - Browser: [e.g. Chrome v64.5.13, Safari v12.0.1]

**Comment by westbrookj** [comment]
Fixed! Decimal precision for the horizontal bar graph tooltips is now 2 places.
